version: '3.9'

services:
  postgres-usuarios:
    image: postgres:15
    container_name: postgres-usuarios
    environment:
      POSTGRES_DB: usuariosdb
      POSTGRES_USER: Espe_2025
      POSTGRES_PASSWORD: Espe_2025.@
    ports:
      - "5432:5432"
    volumes:
      - postgres_usuarios_data:/var/lib/postgresql/data
    networks:
      - moodle-net

  mongodb-cursos:
    image: mongo:6
    container_name: mongodb-cursos
    ports:
      - "27017:27017"
    volumes:
      - mongo_cursos_data:/data/db
    networks:
      - moodle-net

  mysql-calificaciones:
    image: mysql:8
    container_name: mysql-calificaciones
    environment:
      MYSQL_ROOT_PASSWORD: Espe_2025.@
      MYSQL_DATABASE: calificacionesdb
      MYSQL_USER: Espe_2025
      MYSQL_PASSWORD: Espe_2025.@
    ports:
      - "3307:3306"
    volumes:
      - mysql_calificaciones_data:/var/lib/mysql
    networks:
      - moodle-net

  calificaciones-service:
    image: danielllumigusin/calificaciones-microservicios:latest
    container_name: calificaciones-service
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql-calificaciones
      - DB_PORT=3306
      - DB_NAME=calificacionesdb
      - DB_USER=Espe_2025
      - DB_PASSWORD=Espe_2025.@
    depends_on:
      - mysql-calificaciones
    networks:
      - moodle-net

  cursos-service:
    image: danielllumigusin/cursos-microservicios:latest
    container_name: cursos-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb-cursos:27017
    depends_on:
      - mongodb-cursos
    networks:
      - moodle-net

  usuarios-service:
    image: danielllumigusin/usuarios-microservicios:latest
    container_name: usuarios-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-usuarios:5432/usuariosdb
      - SPRING_DATASOURCE_USERNAME=Espe_2025
      - SPRING_DATASOURCE_PASSWORD=Espe_2025.@
    depends_on:
      - postgres-usuarios
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: bridge

volumes:
  postgres_usuarios_data:
  mongo_cursos_data:
  mysql_calificaciones_data:
